### ISSUE TITLE
Simplify consult integration?

### ISSUE THREAD

**Issue by minad** [Overdr0ne/gumshoe#1]
You can probably reuse `consult-global-mark`.

~~~ elisp
(defvar my-markers nil
  "My custom mark ring")

(defun consult-my-markers ()
  (interactive)
  ;; Overwrite the global-mark-ring with my-markers
  (let ((orig-global-mark-ring global-mark-ring)
        (global-mark-ring my-markers))
  (consult--minibuffer-with-setup-hook
      ;; Restore the global-mark-ring in the minibuffer to keep recursive editing intact
      (lambda () (setq global-mark-ring orig-global-mark-ring))
    (consult-global-mark))))
~~~

It could be even simpler if `consult-global-mark` would accept a marker list as argument. I should probably add this to facilitate reusing the command with custom mark rings.

**Comment by Overdr0ne** [comment]
Oh wow, I didn't even realize that command was there. And yes, I would definitely appreciate a consult-global-mark with optional mark list argument. I'll start testing this...

**Comment by Overdr0ne** [comment]
Hey, your suggestion worked really well. Thanks!

https://github.com/Overdr0ne/gumshoe/commit/ce6cc3b88caca0bd47e290ebe450c41830fc7a3e

**Comment by minad** [comment]
I added the argument https://github.com/minad/consult/commit/e8ce2b6aa0022ab9095f061b3085a498f64e0094. This allows much easier reuse for gumshoe and also in other scenarios.

You may even consider to remove `consult-gumshoe` from your package and only document it in the README in order to avoid the `with-eval-load/require` dance. Then your package would be free from completion systems dependencies, which is beneficial for users of other completion systems. I think it is generally good if packages are completion system agnostic and if they have only few dependencies.

~~~ elisp
(defun consult-gumshoe ()
  (interactive)
  (consult-global-mark (ring-elements gumshoe--log))
~~~

**Comment by Overdr0ne** [comment]
Awesome, thank you so much. And I totally agree.
