### ISSUE TITLE
Feature request: Don't make `isearch` and similar commands break the leash

### ISSUE THREAD

**Issue by Walheimat** [Overdr0ne/gumshoe#15]
It's easy to accumulate lots of meaningless entries while performing `isearch`. A few searches can clutter the footprints a lot.

`dogears` has the concept of `dogears-ignore-places-functions` that are called to verify whether a record should be made at all. Maybe that could be an approach here as well?

**Comment by Overdr0ne** [comment]
Oh wow, I hadn't thought of that method of doing things. So for isearch I would add a "currently isearching" predicate, and not track if so. That seems really flexible and easy to implement. I'll get back soon after I think a bit more about what other predicates should be added there by default...

**Comment by Overdr0ne** [comment]
I've added a couple options that allow you to block gumshoe from logging your position, based on major or minor mode, or just with a predicate (gumshoe-ignore-predicates). isearch has been added by default to the gumshoe-ignored-minor-modes. Just let me know if that does not work for you.

**Comment by Overdr0ne** [comment]
Oops, had to fix a bug to allow possibly undefined minor modes to be ignored. Should be okay now...

**Comment by Walheimat** [comment]
I've upgraded just now and will test it. Looks like this should resolve my problem. Thanks!

**Comment by Walheimat** [comment]
Can be closed from my side, no longer have this problem.
